name: 'Basic CI Workflow'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  setup_python:
    name: Set Up Python Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

  setup_js:
    name: Set Up Node.js Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
